DROP TABLE IF EXISTS `orderr`;

CREATE TABLE `orderr` (
	id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    instant DATETIME DEFAULT CURRENT_TIMESTAMP,
	client_id BIGINT(20) NOT NULL,
	address_id BIGINT(20) NOT NULL,
	FOREIGN KEY (client_id) REFERENCES client(id),
	FOREIGN KEY (address_id) REFERENCES address(id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;